---

###############################################
#
# docker でwordpress 環境を作成するyml です
###############################################

- name: docker でwordpress 環境
  hosts: localhost
  gather_facts: true
  remote_user: vagrant
  become: yes
  roles:
    # - docker
    - wordpress
