###############################################
# wordpress 環境をdocker 上で作成します
###############################################

# docker がstart しているかどうか確認




# shell を実行



# document root 作成されているかを確認



# docker compose up -d を実行してwordpress を立ち上げる