---

#podman コマンドによってエラーが発生したたｍ
- name: remove podman and related packages
  yum:
    name:
      - podman
      - podman-docker
      - podman-compose
      - podman-tui
      - buildah
      - skopeo
      - skopeo-containers
      - runc
      - containers-common
    state: absent
    ignore_errors: yes


- name: Download docker repo
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo


- name: install docker in alma 8
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  # when: ansible_distribution == "AlmaLinux" and ansible_distribution_major_version == "8"


- name: install docker compose
  ansible.builtin.shell: curl -L
    "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname
    -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- name: start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
